apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: nexus-repository-manager
    repoURL: https://sonatype.github.io/helm3-charts/
    targetRevision: "64.2.0"
    helm:
      releaseName: registry
      parameters:
      - name: "persistence.storageSize"
        value: "80Gi"
      - name: "image.tag"
        value: "3.68.1"
      values: |
        nexus:
          docker:
            enabled: true
            registries:
              - host: dk.skabrits.duckdns.org
                port: 5000
                secretName: registry-secret

        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 100000m
            cert-manager.io/cluster-issuer: letsencrypt-cluster
            nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hostPath: /
          hostRepo: nx.skabrits.duckdns.org
          tls:
            - secretName: nexus-local-tls
              hosts:
                - nx.skabrits.duckdns.org
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nexus-repo
