apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: "1.8.0"
    helm:
      releaseName: longhorn
      parameters:
      - name: "preUpgradeChecker.jobEnabled"
        value: "false"
      - name: "persistence.defaultClassReplicaCount"
        value: "2"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
