apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-lg-http
  namespace: longhorn-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required '
    cert-manager.io/cluster-issuer: letsencrypt-cluster
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ingressClassName: nginx
  rules:
  - host: skabrits.tplinkdns.com
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /longhorn(/|$)(.*)
  - host: longhorn.skabrits.duckdns.org
    http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /()(.*)
  - http:
      paths:
      - backend:
          service:
            name: longhorn-frontend
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /longhorn(/|$)(.*)
  tls:
  - hosts:
    - skabrits.tplinkdns.com
    - longhorn.skabrits.duckdns.org
    secretName: longhorn-cert
