apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcam-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: helm/stream-base64-webcam/
    repoURL: https://github.com/skabrits/stream-base64-webcam.git
    targetRevision: main
    helm:
      releaseName: grafana
  destination:
    server: "https://kubernetes.default.svc"
    namespace: alarm-control
