apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: searxng
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: searxng
    repoURL: https://charts.searxng.org
    targetRevision: "*"
    helm:
      releaseName: llm
      parameters:
      - name: "searxng.config.server.secret_key"
        value: "f9e603d4191caab069b021fa0568391a33c8a837b470892c64461b5dd12464f4"
      - name: "searxng.config.server.bind_address"
        value: "0.0.0.0"
      - name: "searxng.config.server.image_proxy"
        value: "true"
      - name: "searxng.config.ui.static_use_hash"
        value: "true"
      - name: "searxng.config.search.default_lang"
        value: ""
      - name: "searxng.config.search.formats[0]"
        value: "html"
      - name: "searxng.config.search.formats[1]"
        value: "json"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
