apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lws
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: .
    repoURL: https://github.com/skabrits/lws.git
    targetRevision: "main"
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
