apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: open-webui 
    repoURL: https://helm.openwebui.com/
    targetRevision: "*"
    helm:
      releaseName: llm
      parameters:
      - name: "ollama.enabled"
        value: "false"
      - name: "ollamaUrls[0]"
        value: "192.168.0.154"
      - name: "ollamaUrls[0]"
        value: "192.168.0.154"
      - name: "extraEnvVars[1].name"
        value: "DEFAULT_MODELS"
      - name: "extraEnvVars[1].name"
        value: "DEFAULT_MODELS"
      - name: "extraEnvVars[1].value"
        value: "llama3.1:8b"
      - name: "service.type"
        value: "LoadBalancer"
      - name: "service.annotations.metallb\\.universe\\.tf/loadBalancerIPs"
        value: "192.168.0.155"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ollama
