apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rep-bot
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: repetitor-ptb-worker
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  sources:
  - path: deploy/ptb
    repoURL: https://github.com/polina5935/EGE.git
    targetRevision: main
    helm:
      releaseName: repetitor
      valueFiles:
      - values.yaml
      - ../values.yaml
      - $values/values.yaml
  - repoURL: 'https://github.com/skabrits/repetitor-deploy.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: repetitor-bot
