apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neoj4
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: neo4j
    repoURL: https://github.com/neo4j/helm-charts.git
    targetRevision: "5.24.1"
    helm:
      releaseName: arbitraz
      parameters:
      - name: "neo4j.name"
        value: "arbitraz"
      - name: "neo4j.password"
        value: "test-123"
      - name: "volumes.data.mode"
        value: "defaultStorageClass"
      - name: "services.admin.spec.type"
        value: "LoadBalancer"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
