apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: mysql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: "12.3.5"
    helm:
      releaseName: schedule
      parameters:
      - name: "global.security.allowInsecureImages"
        value: "true"
      - name: "image.registry"
        value: "public.ecr.aws"
      - name: "auth.rootPassword"
        value: "test-123"
      - name: "primary.service.type"
        value: "LoadBalancer"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dev
