# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
  # name: ingress-kib-https
  # namespace: log-system
  # annotations:
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    # nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
# spec:
  # ingressClassName: nginx
  # rules:
  # - http:
      # paths:
      # - path: /logs(/|$)(.*)
        # pathType: Prefix
        # backend:
          # service:
            # name: kibana-kb-http
            # port:
              # number: 443