apiVersion: batch/v1
kind: Job
metadata:
  name: jaeger-elastic-secret
  namespace: observability
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  template:
    spec:
      containers:
      - name: secret-creator
        image: bitnami/kubectl:1.31.1
        command: ["bash", "-c", "PASSWORD=$(kubectl get secret elastic-es-elastic-user -n elastic -o=jsonpath='{.data.elastic}' | base64 --decode) && kubectl create secret generic jaeger-secret --from-literal=ES_PASSWORD=${PASSWORD} --from-literal=ES_USERNAME=elastic -n jaeger --dry-run=client -o yaml | kubectl apply -f -"]
      restartPolicy: Never
  backoffLimit: 4
