apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jae-http
  namespace: log-system
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /jaeger(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: jaeger-el-query
            port:
              number: 16686