apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-el
  namespace: jaeger
spec:
  strategy: production
  agent:
    strategy: DaemonSet
  query:
    options:
      query:
        base-path: /jaeger
  ingress:
    enabled: false
  storage:
    type: elasticsearch
    options:
      es:
        server-urls: https://elastic-es-http.elastic.svc:9200
        tls:
          skip-host-verify: true
        num-shards: 2
        num-replicas: 1
    secretName: jaeger-secret
