apiVersion: v1
kind: ConfigMap
metadata:
  name: example-grafana-datasource
  namespace: perform-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
     grafana_datasource: "1"
data:
 gra_datasources.yaml: |-
   apiVersion: 1
   datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server:80
      isDefault: true
    - name: yesoreyeram-infinity-datasource
      type: yesoreyeram-infinity-datasource
      uid: c4743bbf-2922-4e1d-ba29-5f975b8571c0
      url: ""
      orgId: 1
      basicAuth: false
      basicAuthUser: ""
      isDefault: false
