apiVersion: v1
kind: ConfigMap
metadata:
  name: example-grafana-datasource
  namespace: perform-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
     grafana_datasource: "1"
data:
 gra_datasources.yaml: |-
   apiVersion: 1
   datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server:80
      isDefault: true
    - name: yesoreyeram-infinity-datasource
      type: yesoreyeram-infinity-datasource
      uid: c4743bbf-2922-4e1d-ba29-5f975b8571c0
      url: ""
      orgId: 1
      basicAuth: false
      basicAuthUser: ""
      isDefault: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting
  namespace: perform-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    grafana_alert: "1"
data:
  grafana-alert.yaml: |-
    apiVersion: 1
    groups:
        - orgId: 1
          name: HighPriority
          folder: cluster_alerts
          interval: 1m
          rules:
            - uid: d7c4302b-fae5-4650-9b5a-741295e66e77
              title: Temperature warning
              condition: Temperature above 90
              data:
                - refId: Temperature
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: PBFA97CFB590B2093
                  model:
                    editorMode: code
                    expr: node_hwmon_temp_celsius{chip="platform_nct6775_2592", sensor="temp7"}
                    instant: true
                    intervalMs: 1000
                    legendFormat: '{{node}}'
                    maxDataPoints: 43200
                    range: false
                    refId: Temperature
                - refId: Temperature above 90
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 90
                            type: gt
                          operator:
                            type: and
                          query:
                            params:
                                - C
                          reducer:
                            params: []
                            type: last
                          type: query
                    datasource:
                        type: __expr__
                        uid: __expr__
                    expression: Temperature
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: Temperature above 90
                    type: threshold
              dashboardUid: b0e47bb7-fbec-46e0-909f-2c7c3cb79dc8
              panelId: 1
              noDataState: NoData
              execErrState: Error
              for: 3m
              annotations:
                __dashboardUid__: b0e47bb7-fbec-46e0-909f-2c7c3cb79dc8
                __panelId__: "1"
                summary: Temperature exceeded
              labels:
                severity: critical
                type: cluster_wide
              isPaused: false
        - orgId: 1
          name: Proxy
          folder: cluster_alerts
          interval: 5m
          rules:
            - uid: cf12vrl1ef01sb
              title: Proxy Failed
              condition: B
              data:
                - refId: A
                  relativeTimeRange:
                    from: 600
                    to: 0
                  datasourceUid: PBFA97CFB590B2093
                  model:
                    editorMode: code
                    expr: (increase(proxy_success_total[4m]) > bool 0) * (1-(increase(proxy_failure_total[4m]) > bool 0))
                    instant: true
                    intervalMs: 1000
                    legendFormat: __auto
                    maxDataPoints: 43200
                    range: false
                    refId: A
                - refId: B
                  datasourceUid: __expr__
                  model:
                    conditions:
                        - evaluator:
                            params:
                                - 0
                                - 0
                            type: gt
                          operator:
                            type: and
                          query:
                            params: []
                          reducer:
                            params: []
                            type: avg
                          type: query
                    datasource:
                        name: Expression
                        type: __expr__
                        uid: __expr__
                    expression: $A < 1
                    hide: false
                    intervalMs: 1000
                    maxDataPoints: 43200
                    refId: B
                    type: math
              dashboardUid: ff12v9dtb9b7kf
              panelId: 1
              noDataState: NoData
              execErrState: Error
              for: 5m
              annotations:
                __dashboardUid__: ff12v9dtb9b7kf
                __panelId__: "1"
                summary: Proxy is down
              labels: {}
              isPaused: false
              notification_settings:
                receiver: TG report
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-alerting-policy
  namespace: perform-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    grafana_alert: "1"
data:
  grafana-alert.yaml: |-
    apiVersion: 1
    policies:
        - orgId: 1
          receiver: grafana-default-email
          group_by:
            - grafana_folder
            - alertname
          routes:
            - receiver: TG report
              object_matchers:
                - - severity
                  - =
                  - critical
                - - type
                  - =
                  - cluster_wide
