apiVersion: v1
kind: ConfigMap
metadata:
  name: example-grafana-datasource
  namespace: perform-system
  labels:
     grafana_datasource: "1"
data:
 gra_datasources.yaml: |-
   apiVersion: 1
   datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-server:80
      isDefault: true