apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "7.3.1"
    helm:
      releaseName: grafana
      parameters:
      - name: "service.type"
        value: "ClusterIP"
      - name: "sidecar.dashboards.enabled"
        value: "true"
      - name: "sidecar.datasources.enabled"
        value: "true"
      - name: "sidecar.alerts.enabled"
        value: "true"
      - name: "persistence.storageClassName"
        value: "longhorn"
      - name: "persistence.enabled"
        value: "true"
      - name: "persistence.accessModes[0]"
        value: "ReadWriteMany"
      - name: "grafana\\.ini.server.root_url"
        value: "%(protocol)s://%(domain)s/grafana/" # "%(protocol)s://%(domain)s:%(http_port)s/grafana/"
      - name: "grafana\\.ini.server.domain"
        value: "skabrits.tplinkdns.com"
      - name: "grafana\\.ini.server.serve_from_sub_path"
        value: "true"
      - name: "env.GF_PANELS_DISABLE_SANITIZE_HTML"
        value: "true"
      - name: "env.GF_DASHBOARDS_MIN_REFRESH_INTERVAL"
        value: "0.001s"
      - name: "plugins[0]"
        value: "marcusolsson-dynamictext-panel"
      - name: "plugins[1]"
        value: "yesoreyeram-infinity-datasource"
      - name: "annotations.argocd\\.argoproj\\.io/sync-options"
        value: "Prune=false"
      - name: "annotations.argocd\\.argoproj\\.io/compare-options"
        value: "IgnoreExtraneous"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: perform-system
