apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gra-http
  namespace: perform-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 80
        pathType: Prefix
        path: /grafana(/|$)(.*)
