apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-gra-http
  namespace: perform-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: skabrits.tplinkdns.com
    http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /grafana(/|$)(.*)
  - http:
      paths:
      - backend:
          service:
            name: grafana
            port:
              number: 80
        pathType: ImplementationSpecific
        path: /grafana(/|$)(.*)
