apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic
  namespace: elastic
spec:
  version: docker.elastic.co/eck
  # image: skabrits/elasticsearch:7.10.1
  nodeSets:
    - name: default
      count: 1
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            storageClassName: longhorn
            resources:
              requests:
                storage: 10Gi
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
