apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: pihole
    repoURL: https://mojo2600.github.io/pihole-kubernetes
    targetRevision: "2.35.0"
    helm:
      releaseName: dns-server
      values: |
        serviceWeb:
          type: LoadBalancer
          loadBalancerIP: 192.168.0.146
        serviceDns:
          type: LoadBalancer
          loadBalancerIP: 192.168.0.149
          annotations:
            metallb.universe.tf/allow-shared-ip: pihole-svc
        persistentVolumeClaim:
          enabled: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dns-server
