apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  custom.server: |
    tplinkdns.com {
        template ANY AAAA {
            rcode NOERROR
        }
        forward . 8.8.8.8
    }
    duckdns.org {
        template ANY AAAA {
            rcode NOERROR
        }
        forward . 8.8.8.8
    }
