apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.9.1"
    helm:
      releaseName: my-release
      parameters:
      - name: "controller.replicaCount"
        value: "2"
      - name: "controller.allowSnippetAnnotations"
        value: "true"
        forceString: true
      - name: "controller.extraArgs.tcp-services-configmap"
        value: "ingress-nginx/tcp-services"
      - name: "controller.extraArgs.udp-services-configmap"
        value: "ingress-nginx/udp-services"
      - name: "controller.service.annotations.metallb\\.universe\\.tf/loadBalancerIPs"
        value: "192.168.0.140"
      - name: "controller.service.labels.tplink-ports"
        value: "1"
        forceString: true
      - name: "controller.service.annotations.tplink-ports\\.auto"
        value: "1"
        forceString: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
