apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router-port-configurator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  sources:
  - path: charts/port-configurator/
    repoURL: https://github.com/skabrits/port-configurator.git
    targetRevision: master
    helm:
      releaseName: helper
      parameters:
      - name: "provider.namespace"
        value: "router"
      - name: "provider.name"
        value: "Router"
    valueFiles:
      - $values/deploy/router/values.yaml
  - repoURL: 'https://github.com/skabrits/cluster-sensitive.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: router