apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-port-configurator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: charts/port-configurator/
    repoURL: https://github.com/skabrits/port-configurator.git
    targetRevision: master
    helm:
      releaseName: helper
      parameters:
      - name: "envs.INGRESS_DEPLOYMENT"
        value: "my-release-ingress-nginx-controller"
      - name: "envs.LOG_LEVEL"
        value: "DEBUG"
      - name: "image.pullPolicy"
        value: "Always"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
