apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: "./deploy/"
    repoURL: https://github.com/skabrits/cluster-sensitive.git
    targetRevision: "main"
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "argocd"
