apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chemistry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  sources:
  - path: chemistry-pack/
    repoURL: https://github.com/skabrits/chemistry.git
    targetRevision: main
    helm:
      releaseName: slava
      parameters:
      - name: "resources.requests.cpu"
        value: 1000m
      - name: "resources.requests.memory"
        value: 4Gi
      - name: "resources.limits.cpu"
        value: 3000m
      - name: "resources.limits.memory"
        value: 8Gi
      - name: "storage.size"
        value: 64Gi
      - name: "storage.shm"
        value: 1Gi
      - name: "storage.mode"
        value: "ReadWriteOnce"
      - name: "ingress.hosts[0].paths[0].path"
        value: "/"
      - name: "ingress.hosts[0].paths[0].pathType"
        value: "Prefix"
      - name: "replicaCount"
        value: "1"
      - name: "image.repository"
        value: "skabrits/chemistry-pack-hpc"
      - name: "image.tag"
        value: "1.1.1"
      - name: "image.pullPolicy"
        value: "Always"
      - name: "envs.DISABLE_GPU"
        value: "1"
        forceString: true
      - name: "settings.hpc"
        value: "true"
      valueFiles:
      - $values/deploy/chemistry/values.yaml
  - repoURL: 'https://github.com/skabrits/cluster-sensitive.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chemistry
