apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chemistry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  sources:
  - path: chemistry-pack/
    repoURL: https://github.com/skabrits/chemistry.git
    targetRevision: main
    helm:
      releaseName: slava
      parameters:
      - name: "resources.requests.cpu"
        value: 10500m
      - name: "resources.requests.memory"
        value: 36Gi
      - name: "resources.limits.cpu"
        value: 14000m
      - name: "resources.limits.memory"
        value: 42Gi
      - name: "storage.size"
        value: 64Gi
      - name: "storage.shm"
        value: 8Gi
      - name: "storage.mode"
        value: "ReadWriteOnce"
      - name: "ingress.hosts[0].paths[0].path"
        value: "/"
      - name: "ingress.hosts[0].paths[0].pathType"
        value: "Prefix"
      - name: "replicaCount"
        value: "0"
      - name: "image.tag"
        value: "3.2.0"
      valueFiles:
      - $values/deploy/chemistry/values.yaml
  - repoURL: 'https://github.com/skabrits/cluster-sensitive.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chemistry
