apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolfram-math
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    path: chemistry-pack/
    repoURL: https://github.com/skabrits/chemistry.git
    targetRevision: main
    helm:
      releaseName: wolfram-math
      parameters:
      - name: "resources.requests.cpu"
        value: 8000m
      - name: "pvc.size"
        value: 20Gi
      - name: "ingress.hosts.paths.path"
        value: "/wolfram/"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: wolfram-math
