apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chemistry
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  sources:
  - path: chemistry-pack/
    repoURL: https://github.com/skabrits/chemistry.git
    targetRevision: main
    helm:
      releaseName: slava
      parameters:
      - name: "resources.requests.cpu"
        value: 10000m
      - name: "resources.requests.memory"
        value: 32Gi
      - name: "resources.limits.cpu"
        value: 10000m
      - name: "resources.limits.memory"
        value: 32Gi
      - name: "pvc.size"
        value: 64Gi
      - name: "ingress.hosts[0].paths[0].path"
        value: "/chemistry/"
      - name: "ingress.hosts[0].paths[0].pathType"
        value: "ImplementationSpecific"
      - name: "replicaCount"
        value: "0"
      - name: "image.tag"
        value: "2.0.0"
      valueFiles:
      - $values/deploy/chemistry/values.yaml
  - repoURL: 'https://github.com/skabrits/cluster-sensitive.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: chemistry
