apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  project: default
  source:
    chart: gpu-operator
    repoURL: https://helm.ngc.nvidia.com/nvidia
    targetRevision: "23.9.1"
    helm:
      releaseName: gforce
      parameters:
      - name: "toolkit.env[0].name"
        value: "CONTAINERD_CONFIG"
      - name: "toolkit.env[0].value"
        value: "/var/lib/rancher/k3s/agent/etc/containerd/config.toml"
      - name: "toolkit.env[1].name"
        value: "CONTAINERD_SOCKET"
      - name: "toolkit.env[1].value"
        value: "/run/k3s/containerd/containerd.sock"
      - name: "toolkit.env[2].name"
        value: "CONTAINERD_RUNTIME_CLASS"
      - name: "toolkit.env[2].value"
        value: "nvidia"
      - name: "toolkit.env[3].name"
        value: "CONTAINERD_SET_AS_DEFAULT"
      - name: "toolkit.env[3].value"
        value: "true"
        forceString: true
      - name: "cdi.enabled"
        value: "true"
        forceString: true
      - name: "cdi.default"
        value: "true"
        forceString: true
      - name: "driver.enabled"
        value: "false"
        forceString: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: gpu-operator
