apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    jsonPointers:
    - /rules
    kind: ClusterRole
  - group: kyverno.io
    jqPathExpressions:
    - .spec.rules[] | select(.name|test("autogen-."))
    kind: ClusterPolicy
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: "3.3.4"
    helm:
      releaseName: security
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kyverno
