apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-ist-http
  namespace: istio-system
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10000m
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: istio-ingressgateway
            port:
              number: 80
