apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: modify-pod-runtime
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
    policies.kyverno.io/title: Modify pod runtime
    policies.kyverno.io/category: Mutator
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: pod
    policies.kyverno.io/minversion: "1.11.4"
    kyverno.io/kyverno-version: "1.11.4"
    kyverno.io/kubernetes-version: "1.31"
    policies.kyverno.io/description: >-
      This policy adds runtime class NVIDIA to pods requesting gpu.
spec:
  rules:
    - name: check-paths
      match:
        any:
        - resources:
            kinds:
            - Pod
      preconditions:
        all:
        - key: "{{ request.object.spec.containers[*].resources.limits.\"nvidia.com/gpu\" }}"
          operator: AnyNotIn
          value: ""
        - key: "{{ request.object.spec.runtimeClassName || '' }}"
          operator: Equals
          value: ""
      skipBackgroundRequests: true
      mutate:
        patchStrategicMerge:
          spec:
            runtimeClassName: nvidia
