apiVersion: kubeflow.org/v1beta1
kind: Profile
metadata:
  name: slava-user 
  namespace: kubeflow
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "5"
spec:
  owner:
    kind: User
    name: slava@user.kubeflow   

  resourceQuotaSpec:
   hard:
     cpu: "8"
     memory: 24Gi
     requests.nvidia.com/gpu: "1"
     persistentvolumeclaims: "5"
     requests.storage: "60Gi"
